FROM alpine:3.4

RUN apk add --update gcc musl-dev linux-headers

COPY rbinder.c rbinder.c
COPY uthash.h uthash.h
RUN gcc -o rbinder rbinder.c

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN	addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
	adduser -g "${SERVICE_NAME} user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER} && \
	apk add --update libcap

WORKDIR /
EXPOSE 8080
COPY app /

RUN	chmod +x /app && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /app && \
	setcap 'cap_net_bind_service=+ep' /app

USER ${SERVICE_USER}

CMD ["/rbinder", "/app", "-port=8080"]
